version: '3.8'
services:
  mysql:
    container_name: mysql_container
    image: mysql:8.3.0
    restart: always
    ports:
      - 3306:3306
    networks:
      - foodorder-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foodorder
      MYSQL_USER: user
    volumes:
      - db-data:/var/lib/mysql

  restaurant-backend:
    container_name: backend_container
    image: valmikdocker/vaibhav_food_project:backend
    restart: always
    ports:
      - 5000:5000
    networks:
      - foodorder-network


volumes:
  db-data:

networks:
  restaurant-network: